export const CUSTOMER_SIGNIN_REQUEST = 'CUSTOMER_SIGNIN_REQUEST';
export const CUSTOMER_SIGNIN_REQUEST_SUCCESS = 'CUSTOMER_SIGNIN_REQUEST_SUCCESS';
export const CUSTOMER_SIGNIN_REQUEST_FAILURE = 'CUSTOMER_SIGNIN_REQUEST_FAILURE';
export const CUSTOMER_SIGNIN_CLEAN_REQUEST = 'CUSTOMER_SIGNIN_CLEAN_REQUEST';

export const CUSTOMER_SIGNUP_REQUEST = 'CUSTOMER_SIGNUP_REQUEST';
export const CUSTOMER_SIGNUP_REQUEST_SUCCESS = 'CUSTOMER_SIGNUP_REQUEST_SUCCESS';
export const CUSTOMER_SIGNUP_REQUEST_FAILURE = 'CUSTOMER_SIGNUP_REQUEST_FAILURE';
export const CUSTOMER_SIGNUP_CLEAN_REQUEST = 'CUSTOMER_SIGNUP_CLEAN_REQUEST';
