export const CUSTOMER_PASSWORD_UPDATE_REQUEST = 'CUSTOMER_PASSWORD_UPDATE_REQUEST';
export const CUSTOMER_PASSWORD_UPDATE_REQUEST_SUCCESS = 'CUSTOMER_PASSWORD_UPDATE_REQUEST_SUCCESS';
export const CUSTOMER_PASSWORD_UPDATE_REQUEST_FAILURE = 'CUSTOMER_PASSWORD_UPDATE_REQUEST_FAILURE';

export const CUSTOMER_PASSWORD_CLEAN_REQUEST = 'CUSTOMER_PASSWORD_CLEAN_REQUEST';
