export const PRIMARY_BACKGROUND_COLOR = '#F7F9FB';
export const SECONDARY_BACKGROUND_COLOR = '#0477BF';
export const TERTIARY_BACKGROUND_COLOR = '#FFFFFF';
export const QUATERNARY_BACKGROUND_COLOR = '#D2D4FC';
export const QUINARY_BACKGROUND_COLOR = '#E6F0FF';
export const SENARY_BACKGROUND_COLOR = '#DDE0FD';
export const SEPTENARY_BACKGROUND_COLOR = '#FEEFF8';
export const OCTONARY_BACKGROUND_COLOR = '#F4F5F7';
export const NONARY_BACKGROUND_COLOR = '#CCCCCC';
export const DENARY_BACKGROUND_COLOR = '#E4F0F8';
export const UNDENARY_BACKGROUND_COLOR = '#E4E6F8';
export const DUODENARY_BACKGROUND_COLOR = '#E9F7EF';
export const THRIODENARY_BACKGROUND_COLOR = '#FEF5F5';
export const QUADENARY_BACKGROUND_COLOR = '#0000FF';
export const QUIDENARY_BACKGROUND_COLOR = '#5FAAD9';
export const SENDENARY_BACKGROUND_COLOR = '#048ABF';
export const SEPTDENARY_BACKGROUND_COLOR = '#F2F2F2';

export const PRIMARY_TEXT_COLOR = '#0477BF';
export const SECONDARY_TEXT_COLOR = '#2B2D42';
export const TERTIARY_TEXT_COLOR = '#747E8F';
export const QUATERNARY_TEXT_COLOR = '#262626';
export const QUINARY_TEXT_COLOR = '#FFFFFF';
export const SENARY_TEXT_COLOR = '#F2F2F2';
export const SEPTENARY_TEXT_COLOR = '#14151E';
export const OCTONARY_TEXT_COLOR = '#F02323';
export const NONARY_TEXT_COLOR = '#000000';
export const DENARY_TEXT_COLOR = '#BEBEBE';
export const UNDENARY_TEXT_COLOR = '#6B59ED';
export const DUODENARY_TEXT_COLOR = '#0B8EFE';
export const THRIODENARY_TEXT_COLOR = '#53D574';
export const QUADENARY_TEXT_COLOR = '#A9A9A9';
export const QUIDENARY_TEXT_COLOR = '#212121';
export const SENDENARY_TEXT_COLOR = '#0000FF';


export const PRIMARY_HEADING_COLOR = '#212121';
export const SECONDARY_HEADING_COLOR = '#2B2D42';

export const PRIMARY_BUTTON_COLOR = '#0477BF';
export const SECONDARY_BUTTON_COLOR = '#FFFFFF';
export const TERTIARY_BUTTON_COLOR = '#D2D4FC';
export const QUATERNARY_BUTTON_COLOR = '#0000FF';
export const PRIMARY_BUTTON_TEXT_COLOR = '#FFFFFF';
export const SECONDARY_BUTTON_TEXT_COLOR = '#0477BF';
export const TERTIARY_BUTTON_TEXT_COLOR = '#0000FF';

export const PRIMARY_LABEL_COLOR = '#BEBEBE';
export const SECONDARY_LABEL_COLOR = '#212121';

export const PRIMARY_BORDER_COLOR = '#F2F2F2';
export const SECONDARY_BORDER_COLOR = '#BEBEBE';
export const TERTIARY_BORDER_COLOR = '#0477BF';
export const QUATERNARY_BORDER_COLOR = '#D2D4FC';
export const QUINARY_BORDER_COLOR = '#F7F9FB';
export const SENARY_BORDER_COLOR = '#FFFFFF';
export const SEPTENARY_BORDER_COLOR = '#F4F5F7';
export const OCTONARY_BORDER_COLOR = '#CCCCCC';
export const NONARY_BORDER_COLOR = '#F5FCFF';
export const DENARY_BORDER_COLOR = '#747E8F';
export const UNDENARY_BORDER_COLOR = '#0000FF';
export const DUODENARY_BORDER_COLOR = '#6B59ED';
export const THRIODENARY_BORDER_COLOR = '#048ABF';
export const QUIDENARY_BORDER_COLOR = '#5FAAD9';


export const PRIMARY_INPUT_TEXT_COLOR = '#212121';
export const SECONDARY_INPUT_TEXT_COLOR = '#BEBEBE';
export const PRIMARY_INPUT_TEXT_BACKGROUND_COLOR = '#FFFFFF';
export const SECONDARY_INPUT_TEXT_BACKGROUND_COLOR = '';

export const PRIMARY_ERROR_COLOR = 'red';

export const PRIMARY_SUCCESS_COLOR = 'green';


