export const CUSTOMER_FUND_TRANSFER_REQUEST = 'CUSTOMER_FUND_TRANSFER_REQUEST';
export const CUSTOMER_FUND_TRANSFER_REQUEST_SUCCESS = 'CUSTOMER_FUND_TRANSFER_REQUEST_SUCCESS';
export const CUSTOMER_FUND_TRANSFER_REQUEST_FAILURE = 'CUSTOMER_FUND_TRANSFER_REQUEST_FAILURE';

export const CUSTOMER_FUND_TRANSFER_CLEAN_REQUEST = 'CUSTOMER_FUND_TRANSFER_CLEAN_REQUEST';

export const CUSTOMER_PAID_AMOUNT_REQUEST = 'CUSTOMER_PAID_AMOUNT_REQUEST';
export const CUSTOMER_PAID_AMOUNT_REQUEST_SUCCESS = 'CUSTOMER_PAID_AMOUNT_REQUEST_SUCCESS';
export const CUSTOMER_PAID_AMOUNT_REQUEST_FAILURE = 'CUSTOMER_PAID_AMOUNT_REQUEST_FAILURE';

export const CUSTOMER_PAID_AMOUNT_CLEAN_REQUEST = 'CUSTOMER_PAID_AMOUNT_CLEAN_REQUEST';
