export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST';
export const PROFILE_FETCH_REQUEST_SUCCESS = 'PROFILE_FETCH_REQUEST_SUCCESS';
export const PROFILE_FETCH_REQUEST_FAILURE = 'PROFILE_FETCH_REQUEST_FAILURE';
export const PROFILE_CLEAN_REQUEST = 'PROFILE_CLEAN_REQUEST';
