export const CUSTOMER_PROFILE_FETCH_REQUEST = 'CUSTOMER_PROFILE_FETCH_REQUEST';
export const CUSTOMER_PROFILE_FETCH_REQUEST_SUCCESS = 'CUSTOMER_PROFILE_FETCH_REQUEST_SUCCESS';
export const CUSTOMER_PROFILE_FETCH_REQUEST_FAILURE = 'CUSTOMER_PROFILE_FETCH_REQUEST_FAILURE';

export const CUSTOMER_PROFILE_UPDATE_REQUEST = 'CUSTOMER_PROFILE_UPDATE_REQUEST';
export const CUSTOMER_PROFILE_UPDATE_REQUEST_SUCCESS = 'CUSTOMER_PROFILE_UPDATE_REQUEST_SUCCESS';
export const CUSTOMER_PROFILE_UPDATE_REQUEST_FAILURE = 'CUSTOMER_PROFILE_UPDATE_REQUEST_FAILURE';

export const CUSTOMER_PROFILE_CLEAN_REQUEST = 'CUSTOMER_PROFILE_CLEAN_REQUEST';
