export const BANK_FETCH_REQUEST = 'BANK_FETCH_REQUEST';
export const BANK_FETCH_REQUEST_SUCCESS = 'BANK_FETCH_REQUEST_SUCCESS';
export const BANK_FETCH_REQUEST_FAILURE = 'BANK_FETCH_REQUEST_FAILURE';

export const BANK_CLEAN_REQUEST = 'BANK_CLEAN_REQUEST';

export const CUSTOMER_BANK_FETCH_REQUEST = 'CUSTOMER_BANK_FETCH_REQUEST';
export const CUSTOMER_BANK_FETCH_REQUEST_SUCCESS = 'CUSTOMER_BANK_FETCH_REQUEST_SUCCESS';
export const CUSTOMER_BANK_FETCH_REQUEST_FAILURE = 'CUSTOMER_BANK_FETCH_REQUEST_FAILURE';

export const CUSTOMER_BANK_ADD_REQUEST = 'CUSTOMER_BANK_ADD_REQUEST';
export const CUSTOMER_BANK_ADD_REQUEST_SUCCESS = 'CUSTOMER_BANK_ADD_REQUEST_SUCCESS';
export const CUSTOMER_BANK_ADD_REQUEST_FAILURE = 'CUSTOMER_BANK_ADD_REQUEST_FAILURE';

export const CUSTOMER_BANK_CLEAN_REQUEST = 'BANK_CLEAN_REQUEST';
